<?php
include_once(VIEW . 'Header.phtml');
?>

    <audio id="audio" preload="none" tabindex="0">

        Your browser does not support HTML5 audio.
    </audio>

    <div class="player">

        <div class="large-toggle-btn">
            <i class="large-play-btn"><span class="screen-reader-text">Large toggle button</span></i>
        </div>
        <!-- /.play-box -->

        <div class="info-box">
            <div class="track-info-box">
                <div class="track-title-text"></div>
                <div class="audio-time">
                    <span class="current-time">00:00</span> /
                    <span class="duration">00:00</span>
                </div>
            </div>
            <!-- /.info-box -->

            <div class="progress-box">
                <div class="progress-cell">
                    <div class="progress">
                        <div class="progress-buffer"></div>
                        <div class="progress-indicator"></div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.progress-box -->

        <div class="controls-box">
            <i class="previous-track-btn disabled zpet"><span class="screen-reader-text">Previous track button</span></i>
            <i class="next-track-btn dopredu"><span class="screen-reader-text">Next track button</span></i>
        </div>
        <!-- /.controls-box -->

    </div>
    <!-- /.player -->

    <div class="play-list">

    </div>



    <script  src="js/index.js"></script>

<?php
include_once(VIEW . 'Footer.phtml');
?>